- name: Remove Etcd TLS Files
  shell:  sudo /opt/scripts/remove_certs.sh {{root_etcd_file}}*/

- name: Drop Etcd External Path
  shell:  sudo /opt/scripts/drop_etcd_port.sh {{etcd_port_1}} {{etcd_port_2}}